rotki/ui-library-compat

- src/components/logos/Logo.stories.ts
- src/components/logos/Logo.vue
> feat: update logo with customsrc

- src/components/alerts/Alert.vue
- src/theme/index.ts
> feat: improvement for alert

- src/components/logos/Logo.vue
- src/components/steppers/StepperCustomIcon.vue
- src/composables/theme.ts
> fix: adjust color to support custom theme

- scripts/generate-icons.cjs
- src/components/alerts/Alert.vue
- src/components/forms/text-field/TextField.vue
- src/components/icons/Icon.vue
(cherry picked from commit 54c04c3367a7e328322a2b819c7226150cb7a479)
Closes #(issue_number)
> refactor: adds icon type for autocompletion

- .eslintrc-auto-import.json
- example/cypress/e2e/data-table.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/DataTableView.vue
- src/components/forms/select/SimpleSelect.spec.ts
- src/components/forms/select/SimpleSelect.stories.ts
- src/components/forms/select/SimpleSelect.vue
- src/components/index.ts
- src/components/tables/DataTable.spec.ts
- src/components/tables/DataTable.stories.ts
- src/components/tables/DataTable.vue
- src/components/tables/TablePagination.vue
- src/composables/icons.ts
- src/utils/helpers.ts
> feat(DataTable): backports datatable to vue 2

- example/cypress/e2e/card.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/CardView.vue
- example/src/views/DataTableView.vue
- example/src/views/ProgressView.vue
- example/src/views/TextFieldView.vue
- example/src/views/TooltipView.vue
- src/components/cards/Card.spec.ts
- src/components/cards/Card.stories.ts
- src/components/cards/Card.vue
- src/components/cards/CardHeader.vue
- src/components/index.ts
> feat: backport card component to vue 2

- example/src/views/DataTableView.vue
- src/components/chips/Chip.vue
- src/components/index.ts
- src/components/tables/DataTable.vue
- src/components/tabs/tab/Tab.vue
- src/components/tabs/tabs/Tabs.vue
> Backporting changes from main ui-library

- src/components/buttons/button/Button.vue
> fix: update loading state in button

- src/components/tables/TablePagination.vue
> fix: table pagination footer

- src/components/overlays/tooltip/Tooltip.spec.ts
- src/composables/popper.ts
> fix: tooltip timeout bug

- src/components/tables/DataTable.vue
> Update DataTable component

- package.json
> chore: release v0.5.0

- src/components/chips/Chip.vue
> fix(Chip): add default slot

- package.json
> chore: release v0.5.1

- package.json
> chore: release v0.5.2

- src/components/tables/DataTable.stories.ts
- src/components/tables/DataTable.vue
> feat: add striped props to table

- src/components/cards/CardHeader.vue
> fix(Card): change card header to h6

- example/src/views/TextFieldView.vue
- src/components/forms/revealable-text-field/RevealableTextField.stories.ts
- src/components/forms/revealable-text-field/RevealableTextField.vue
- src/components/forms/text-field/TextField.spec.ts
- src/components/forms/text-field/TextField.stories.ts
- src/components/forms/text-field/TextField.vue
> feat: adjust text field, add custom colour and show success message

- src/components/divider/Divider.spec.ts
- src/components/divider/Divider.stories.ts
- src/components/divider/Divider.vue
- src/components/index.ts
- src/style.scss
> feat: divider component

- example/src/views/ButtonView.vue
- src/components/buttons/button-group/ButtonGroup.spec.ts
- src/components/buttons/button-group/ButtonGroup.vue
- src/components/forms/text-field/TextField.vue
> Feat: add button group gap prop

- package.json
> chore: release v0.7.0

- src/components/buttons/button-group/ButtonGroup.vue
- src/components/buttons/button/Button.vue
- src/index.ts
> Add missing prop defaults and expose context colors type

- example/src/views/TextFieldView.vue
- src/composables/popper.ts
update open state so that DOM node is removed on fast cursor move
> fix(Tooltip): tooltip node cleanup

- example/cypress/e2e/overlays/tooltip.cy.ts
- example/src/views/TooltipView.vue
- src/components/overlays/tooltip/Tooltip.spec.ts
- src/components/overlays/tooltip/Tooltip.vue
> fix(Tooltip): remove the wrapper div from activator slot

- package.json
> chore: release v0.7.2

- example/src/views/ButtonView.vue
- src/components/buttons/button-group/ButtonGroup.stories.ts
- src/components/buttons/button-group/ButtonGroup.vue
- src/components/steppers/FooterStepper.vue
and add active color to button group
> Remove interaction from stepper

- example/src/assets/main.css
- example/src/components/AppNav.vue
- example/src/views/ButtonView.vue
- src/components/buttons/button/Button.vue
> chore: increase contrast of primary button

- example/src/views/CheckboxView.vue
- src/components/buttons/button/Button.vue
- src/components/chips/Chip.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/overlays/badge/Badge.vue
> style: adjust colors for some components

- package.json
> chore: release v0.7.4

- src/components/tables/DataTable.vue
> fix: enable text wrapping on table data cells

- src/components/overlays/tooltip/Tooltip.vue
> feat: add listeners for <RuiTooltip />

- src/components/cards/Card.vue
- src/components/cards/CardHeader.vue
> feat: update card subheader style, add  prop

- example/src/views/TextFieldView.vue
- src/components/forms/revealable-text-field/RevealableTextField.vue
- src/components/forms/text-field/TextField.spec.ts
- src/components/forms/text-field/TextField.stories.ts
- src/components/forms/text-field/TextField.vue
> feat: add clearable props for text field

- .eslintrc-auto-import.json
- example/src/views/CheckboxView.vue
- example/src/views/RadioView.vue
- example/src/views/TextFieldView.vue
- src/components/forms/checkbox/Checkbox.spec.ts
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio-group/RadioGroup.spec.ts
- src/components/forms/radio-button/radio-group/RadioGroup.vue
- src/components/forms/radio-button/radio/Radio.spec.ts
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/text-field/TextField.spec.ts
- src/components/forms/text-field/TextField.vue
- src/components/helpers/FormTextDetail.vue
- src/utils/form-text-detail.ts
> feat: adjust errorMessages and successMessages to accept string

- src/components/forms/radio-button/radio-group/RadioGroup.vue
> feat: add label for radio group

- src/components/cards/Card.vue
> fix: scope card child style

- example/src/App.vue
- example/src/router/index.ts
- example/src/views/TextAreaView.vue
- src/components/forms/radio-button/radio/Radio.stories.ts
- src/components/forms/text-area/TextArea.spec.ts
- src/components/forms/text-area/TextArea.stories.ts
- src/components/forms/text-area/TextArea.vue
- src/components/forms/text-field/TextField.vue
- src/components/index.ts
> Feat: add text area component

- package.json
> Bump to 0.8.3

- .eslintrc-auto-import.json
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/text-area/TextArea.vue
- src/components/forms/text-field/TextField.vue
- src/utils/helpers.ts
> Feat: inherit root attributes

- package.json
> chore: release v0.8.4

- src/components/chips/Chip.vue
> fix(Chip): add type=button to chip close button

- package.json
> chore: release v0.9.1

- src/components/tables/DataTable.vue
> fix(DataTable): change row item type to any

- src/components/cards/Card.vue
> style(Card): adjust Card footer padding

- example/src/views/ChipView.vue
- src/components/chips/Chip.stories.ts
- src/components/chips/Chip.vue
> fix(Chip)!: rename prop 'label' to 'tile'

- src/components/buttons/button/Button.stories.ts
- src/components/buttons/button/Button.vue
> feat(Button): add variant "list" to button

- package.json
> chore: release v0.10.0

- .storybook/app.ts
- README.md
- example/src/main.ts
- src/index.ts
> refactor!: change library how initialization happens

- .eslintrc-auto-import.json
- example/cypress/e2e/data-table.cy.ts
- example/src/main.ts
- example/src/views/DataTableView.vue
- src/components/forms/checkbox/Checkbox.stories.ts
- src/components/index.ts
- src/components/overlays/badge/Badge.spec.ts
- src/components/tables/DataTable.spec.ts
- src/components/tables/DataTable.stories.ts
- src/components/tables/DataTable.vue
- src/components/tables/ExpandButton.vue
- src/components/tables/TablePagination.vue
- src/composables/sticky-header.ts
> Feat: table sticky and expandable row

- .eslintrc-auto-import.json
- example/src/main.ts
- example/src/stores/counter.ts
- src/components/tables/DataTable.spec.ts
- src/components/tables/DataTable.vue
- src/composables/defaults/table.ts
- src/index.ts
> feat(DataTable): add items per page global settings

- package.json
> chore: release v0.11.0

- package.json
> chore: release v0.12.0

- package.json
> chore: release v0.13.0

- .eslintrc-auto-import.json
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/BreakpointView.vue
- src/composables/breakpoint.ts
- src/composables/index.ts
> feat(useBreakpoint): tailwind breakpoint composable

- package.json
> chore: release v0.14.0

- src/components/tabs/tabs/Tabs.vue
Fix issue where selected tab reset to `0` if the route changed.
> fix: tab issue when route changed

- .github/workflows/ci.yml
- example/cypress.config.ts
> ci: enable cypress video uploading

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
> chore: update actions versions

- src/components/buttons/button/Button.vue
> style(Button): adjust padding for list button

- package.json
> chore: release v0.15.0

- src/components/forms/checkbox/Checkbox.vue
- src/components/tables/DataTable.vue
- src/components/tables/TableHead.vue
on loading, fix the issue where column size changes
> Fix table loading column size

- src/components/tables/DataTable.vue
> fix(DataTable)!: adjust group header slot schema

- src/components/forms/text-field/TextField.vue
> fix(TextField): styling bug for text-field label

- src/components/tables/DataTable.spec.ts
- src/components/tables/DataTable.vue
> fix(DataTable): reset page to 1 when search value is changed

- example/cypress/e2e/forms/radio.cy.ts
- example/cypress/e2e/forms/switch.cy.ts
- example/src/App.vue
- example/src/main.ts
- example/src/router/index.ts
- example/src/views/SwitchView.vue
- src/components/forms/switch/RuiSwitch.spec.ts
- src/components/forms/switch/RuiSwitch.stories.ts
- src/components/forms/switch/RuiSwitch.vue
- src/components/index.ts
> Feat: switch component

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
> ci: update pnpm/action-setup and codecov-action

- example/package.json
- package.json
> chore: release v0.17.0

- src/index.ts
> fix: make table defaults partial

- src/components/tables/DataTable.spec.ts
- src/components/tables/TablePagination.vue
> fix: revert page selection to text to improve performance

- src/components/forms/text-field/TextField.stories.ts
- src/components/forms/text-field/TextField.vue
> fix: text field label overflowing if it's too long

- src/components/forms/switch/RuiSwitch.vue
> style: improve styling for Switch

- example/cypress/e2e/overlays/menu.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/MenuView.vue
- src/components/index.ts
- src/components/overlays/menu/Menu.spec.ts
- src/components/overlays/menu/Menu.stories.ts
- src/components/overlays/menu/Menu.vue
- src/components/overlays/teleport-container.ts
- src/components/overlays/tooltip/Tooltip.spec.ts
- src/components/overlays/tooltip/Tooltip.stories.ts
- src/components/overlays/tooltip/Tooltip.vue
- src/composables/popper.ts
> feat(Menu): implement menu component

- src/components/overlays/menu/Menu.spec.ts
> test: update test for menu

- src/components/forms/switch/RuiSwitch.vue
> style(Switch): update style for the highlight

- src/components/overlays/teleport-container.ts
- src/index.ts
> fix(Teleport): teleport use different instance

- src/components/tables/DataTable.vue
> fix(DataTable): fix sorting for BigNumber value

- example/cypress/e2e/forms/slider.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/SliderView.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/slider/Slider.spec.ts
- src/components/forms/slider/Slider.stories.ts
- src/components/forms/slider/Slider.vue
- src/components/forms/switch/RuiSwitch.vue
- src/components/index.ts
> feat(Slider): create slider component

- example/cypress/e2e/accordions.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/AccordionView.vue
- src/components/accordions/accordion/Accordion.spec.ts
- src/components/accordions/accordion/Accordion.vue
- src/components/accordions/accordions/Accordions.spec.ts
- src/components/accordions/accordions/Accordions.stories.ts
- src/components/accordions/accordions/Accordions.vue
- src/components/index.ts
- src/components/tabs/tabs/Tabs.spec.ts
> feat(Accordions): implement accordions components

- src/components/accordions/accordion/Accordion.vue
> fix(Accordion): fix wrong accordion content class

- src/components/logos/Logo.stories.ts
- src/components/logos/Logo.vue
> fix(Logo): add fallback mechanism for customSrc

- src/components/forms/checkbox/Checkbox.vue
- src/components/tables/DataTable.vue
> feat(DataTable): allow shift selection for table checkboxes

- example/src/views/DataTableView.vue
- src/components/forms/select/RuiMenuSelect.vue
- src/components/tables/DataTable.vue
- src/components/tables/TablePagination.vue
also add hidden input for page number and limit on table pagination
> refactor: add flag for specifying the position of expand button for rows and groups

- example/src/views/DataTableView.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/tables/DataTable.vue
> feat(DataTable): multi page select for table and small fix for shift select

- example/cypress/e2e/data-table.cy.ts
- example/src/views/DataTableView.vue
- src/components/tables/DataTable.vue
- src/components/tables/TableHead.vue
also move empty table loader to the tbody
> fix(DataTable): show body prepend and prepend slots at all times

- example/package.json
- package.json
> chore: release v0.22.5

- example/package.json
- package.json
> chore: release v0.22.6

- example/src/views/DataTableView.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/tables/DataTable.vue
> fix(DataTable): remove selection when row is deleted for single page select

- example/package.json
- package.json
> chore: release v0.22.7

- example/package.json
- package.json
> chore: release v0.22.8

- example/src/views/MenuView.vue
- src/components/forms/select/RuiMenuSelect.vue
> refactor(RuiMenuSelect): allow primitives as options

- example/src/views/MenuView.vue
- src/components/forms/select/RuiMenuSelect.spec.ts
- src/components/forms/select/RuiMenuSelect.vue
> fix: remove returnPrimitive and replace with check of keyAttr

- example/src/views/MenuView.vue
- src/components/tables/DataTable.spec.ts
- src/components/tables/TablePagination.vue
> fix(TablePagination): use primitives as model, add more tests

- src/components/forms/select/RuiMenuSelect.vue
> fix(RuiMenuSelect): adjust focus styles, add custom item height prop

- example/cypress/e2e/overlays/menu.cy.ts
- example/src/views/MenuView.vue
- src/components/forms/select/RuiMenuSelect.spec.ts
- src/components/forms/select/RuiMenuSelect.vue
- src/components/overlays/menu/Menu.vue
- src/composables/dropdown-menu.ts
> Fix: menu select adjustments

- src/components/overlays/menu/Menu.stories.ts
- src/components/overlays/menu/Menu.vue
> feat(Menu): add props to keep menu when click outside

- src/components/tabs/tabs/Tabs.vue
> fix(Tabs): "active" props not added when "tabValue" is defined

- example/src/views/IconView.vue
- src/components/logos/Logo.spec.ts
- src/components/logos/Logo.stories.ts
- src/components/logos/Logo.vue
- src/components/tabs/tabs/Tabs.vue
- src/utils/helpers.ts
part of https://github.com/orgs/rotki/projects/11/views/2?pane=issue&itemId=58082972
> fix(Logo): make logo component fetch data directly from data repo

- src/components/steppers/FooterStepper.vue
> refactor(FooterStepper): adjust gap between stepper and buttons

- example/package.json
- example/src/views/MenuView.vue
- package.json
> chore: release v0.22.17

- example/src/views/MenuView.vue
- src/components/forms/slider/Slider.vue
- src/components/forms/switch/RuiSwitch.vue
- src/components/steppers/FooterStepper.vue
> Some commits

- example/package.json
- package.json
> chore: release v0.22.18

- src/components/tables/DataTable.vue
> feat(DataTable): add itemClass prop to set class for each row

- example/cypress/e2e/overlays/bottom-sheet.cy.ts
- example/cypress/e2e/overlays/dialog.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/BottomSheetView.vue
- example/src/views/DialogView.vue
- src/components/index.ts
- src/components/overlays/bottom-sheet/BottomSheet.spec.ts
- src/components/overlays/bottom-sheet/BottomSheet.stories.ts
- src/components/overlays/bottom-sheet/BottomSheet.vue
- src/components/overlays/dialog/Dialog.spec.ts
- src/components/overlays/dialog/Dialog.stories.ts
- src/components/overlays/dialog/Dialog.vue
> feat(Dialog): introduce Dialog and BottomSheet components

- package.json
- src/components/forms/text-area/TextArea.vue
- src/components/forms/text-field/TextField.vue
> fix(TextField): fix border color on hover state

- example/package.json
- package.json
> chore: release v0.23.0

- src/components/overlays/dialog/Dialog.vue
> fix(Dialog): ignore input listeners

- example/src/views/MenuView.vue
- src/components/forms/select/RuiMenuSelect.vue
- src/components/index.ts
- src/components/overlays/bottom-sheet/BottomSheet.vue
> fix(MenuSelect): set full-width automatically

- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(AutoComplete): set clearable prop to false by default

- src/components/overlays/navigation-drawer/NavigationDrawer.vue
> fix(NavigationDrawer): adjust z-index

- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(AutoComplete): cannot choose the option in safari

- example/cypress/e2e/overlays/notification.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/NotificationView.vue
- src/components/index.ts
- src/components/overlays/notification/Notification.spec.ts
- src/components/overlays/notification/Notification.stories.ts
- src/components/overlays/notification/Notification.vue
> feat: introduces Notification component

- src/components/overlays/notification/Notification.stories.ts
- src/components/overlays/notification/Notification.vue
> fix(Notification): adjusts top to avoid toolbar in app

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(AutoComplete): broken AutoComplete in certain case

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/utils/is-equal.ts
> fix(AutoComplete): fix breaking UX when user is typing

- src/components/tables/TablePagination.vue
> fix(DataTable): disable pagination buttons on loading

- example/package.json
- package.json
> chore: release v1.0.11
