rotki/ui-library-compat

src/components/forms/revealable-text-field/RevealableTextField.vue

fix(RevealableTextField): replaces useListeners to avoid test issue

---

.eslintrc-auto-import.json
example/cypress/e2e/tabs.cy.ts
example/src/App.vue
example/src/main.ts
example/src/router/index.ts
example/src/views/TabView.vue
package.json
pnpm-lock.yaml
src/components/VRender.ts
src/components/buttons/button/Button.vue
src/components/index.ts
src/components/steppers/StepperCustomIcon.vue
src/components/tabs/tab-item/TabItem.spec.ts
src/components/tabs/tab-item/TabItem.vue
src/components/tabs/tab-items/TabItems.spec.ts
src/components/tabs/tab-items/TabItems.vue
src/components/tabs/tab/Tab.spec.ts
src/components/tabs/tab/Tab.vue
src/components/tabs/tabs/Tabs.spec.ts
src/components/tabs/tabs/Tabs.stories.ts
src/components/tabs/tabs/Tabs.vue
tests/stubs/RouterLinkStub.ts
vite.config.ts

Compat of https://github.com/rotki/ui-library/pull/107

feat: tabs component

---

src/components/overlays/tooltip/Tooltip.vue

fix(Tooltip): activator element inherits width from wrapper

---

src/components/buttons/button-group/ButtonGroup.vue

Fix this error:
```
dialog.ts:28 TypeError: Cannot set properties of undefined (setting 'active')
at index-aa6117f3.js:383:20
at Array.map (<anonymous>)
at VueComponent.<anonymous> (index-aa6117f3.js:380:71)
at Watcher2.get (vue.runtime.esm.js:3446:33)
at Watcher2.evaluate (vue.runtime.esm.js:3547:27)
at get value [as value] (vue.runtime.esm.js:1388:29)
at Object.get [as children] (vue.runtime.esm.js:1201:28)
at Proxy.dr2 (index-aa6117f3.js:426:15)
at Vue2._render (vue.runtime.esm.js:2684:28)
at VueComponent.updateComponent (vue.runtime.esm.js:3875:27)
```

fix: error from button group

---

src/components/buttons/button/Button.spec.ts
src/components/buttons/button/Button.stories.ts
src/components/buttons/button/Button.vue

this will help avoid native form submission when rui-button is used in a form element without specifying a type

fix: add type prop and default to button

---

example/cypress/e2e/data-table.cy.ts
example/src/assets/main.css
example/src/main.ts
src/components/tables/DataTable.vue
src/composables/sticky-header.ts

fix: external pagination, and sticky table header

---

src/composables/sticky-header.ts

quick fix to scroll fixed header on table content scroll

fix: on wide tables, make fixed header position properly on horizontal scroll in the table

---

example/src/views/DataTableView.vue
src/components/tables/DataTable.vue

(other than body)
Paginating a table inside a modal when there's a scroll should no longer scroll body, should scroll to top inside the modal.

refactor: add scroll control, when table is inside vertically scrollable container

---

example/cypress/e2e/chip.cy.ts
example/cypress/e2e/forms/autocomplete.cy.ts
example/src/views/AutoCompleteView.vue
example/src/views/ChipView.vue
src/components/chips/Chip.vue
src/components/forms/auto-complete/RuiAutoComplete.spec.ts
src/components/forms/auto-complete/RuiAutoComplete.vue
src/components/forms/select/RuiMenuSelect.vue
src/composables/dropdown-menu.ts
src/composables/popper.ts

feat(AutoComplete): add some missing props

---

example/cypress/e2e/forms/autocomplete.cy.ts
example/src/views/AutoCompleteView.vue
src/components/forms/auto-complete/RuiAutoComplete.spec.ts
src/components/forms/auto-complete/RuiAutoComplete.vue
src/components/overlays/menu/Menu.vue
src/composables/dropdown-menu.ts

feat(AutoComplete): allow AutoComplete to accept custom value

---

src/components/forms/auto-complete/RuiAutoComplete.vue
src/components/overlays/menu/Menu.vue
src/composables/dropdown-menu.ts
tests/setup-files/setup.ts

fix(AutoComplete): some issues

---

example/cypress/e2e/overlays/navigation-drawer.cy.ts
example/src/App.vue
example/src/router/index.ts
example/src/views/NavigationDrawerView.vue
src/components/index.ts
src/components/overlays/Teleport.ts
src/components/overlays/dialog/Dialog.vue
src/components/overlays/navigation-drawer/NavigationDrawer.spec.ts
src/components/overlays/navigation-drawer/NavigationDrawer.stories.ts
src/components/overlays/navigation-drawer/NavigationDrawer.vue
src/utils/helpers.ts

feat(NavigationDrawer): introduce NavigationDrawer component

---

src/components/forms/auto-complete/RuiAutoComplete.vue

fix(NavigationDrawer): remove unncessary search input selection

---

src/components/overlays/navigation-drawer/NavigationDrawer.vue

fix(NavigationDrawer): adjust z-index on bigger screen

---

src/composables/theme.ts

fix(Theme): fix slow app when the theme is changed

---

src/components/alerts/Alert.vue

fix(Alert): improve visiblity for some alerts

---

src/components/overlays/menu/Menu.vue

fix(Menu): stopPropagation onEscape only if needed

---

src/components/forms/auto-complete/RuiAutoComplete.spec.ts
src/components/forms/auto-complete/RuiAutoComplete.vue

fix(AutoComplete): weird style when it's not focused anymore

---

src/components/forms/auto-complete/RuiAutoComplete.spec.ts
src/components/forms/auto-complete/RuiAutoComplete.vue
src/composables/dropdown-menu.ts

fix(AutoComplete): fix UX to open menu after autocomplete focus

---

src/components/tabs/tab/Tab.vue
src/components/tabs/tabs/Tabs.spec.ts
src/components/tabs/tabs/Tabs.vue

fix(Tabs): change tab-value to value

---

src/components/forms/auto-complete/RuiAutoComplete.vue
src/composables/dropdown-menu.ts

fix(AutoComplete): error getText & getIdentifier used before initialized

---

src/components/forms/auto-complete/RuiAutoComplete.spec.ts
src/components/forms/auto-complete/RuiAutoComplete.vue

fix(AutoComplete): improve UX onEnter

---

src/components/forms/auto-complete/RuiAutoComplete.vue

fix(AutoComplete): give minHeight for menu to prevent items clipped
